name: expenses_app
description: A new Flutter project for tracking expenses
publish_to: 'none' 
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true